### ISSUE TITLE
引用后展示太模糊 如何提高清晰度呢？

### ISSUE THREAD

**Issue by kaleai** [chendishen/react-live2d#10]
示例demo也是比较模糊的

**Comment by chendishen** [comment]
这个其实跟你引入的资源相关，资源比较高清的也会比较大。实例的网站超级低配，放高清资源得很久才能看~

**Comment by kaleai** [comment]
我本地跑起来也是比较模糊，但看资源还是挺清晰的。是否可以理解此项目中提供的的资源还是比较小，所以跑起来是模糊的，而非采样率问题

**Comment by chendishen** [comment]
@tianzhijiexian 我忽然间想起，这个sdk当时我调试的时候，的确发现高频动作、打点数过多的动画。会导致浏览器编译到一定程度的时候阻塞了继续渲染执行，当时我做了个小小的优化去避免了这种直接在第三方打开、终端设备不确定配置的情况下去无限运行更大的资源。因为本身日本这个sdk，我看目前应用于生产大多数情况下都是在移动端设备，所以这个问题浏览器支持跟渲染端的写法都有一定关系。。总的来说这个暂时无法避免。

**Comment by kaleai** [comment]
感谢回复，十分感谢
