### ISSUE TITLE
如果看板娘资源未加载完成，再次点击切换看板娘的按钮，会报错

### ISSUE THREAD

**Issue by weijie-he** [chendishen/react-live2d#2]
某些看板娘资源较大，加载速度比较慢（例如[live2d-model](https://github.com/chendishen/live2d-model)仓库下的 kubo_2 模型），如果在看板娘资源未加载完成前，再次点击切换看板娘的按钮，会报错
![image](https://user-images.githubusercontent.com/16081489/93562505-bb4e7000-f9b8-11ea-93f8-0ec0f9c910e1.png)

**Comment by chendishen** [comment]
模型和动作的重载和残留，甚至导致几次切换之后，前边好几个的某些动作仍然未清除。针对这个，最后决定在切换模型时（新模型未加载完成时）添加了透明蒙层去禁止再次触发任何操作
