### ISSUE TITLE
How to remove modal?

### ISSUE THREAD

**Issue by kfnx** [chendishen/react-live2d#8]
I want to remove modal that pop when user click live2d, is that possible?
I read the readme but I don't quite understand

**Comment by ElmouradiAmine** [comment]
You can overwrite the css of the modal by setting the opacity to 0 or dynamically remove it using javascript.
My solution was to add in my index.css the selector : ```#live2d-print``` and set the opacity to 0.
The modal will be still available in the dom but not visible for the user. This is the only workaround I found.
